# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ua_bugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='BugPost',
        ),
        migrations.RenameModel(
            old_name='Subject',
            new_name='BugSubject',
        ),
        migrations.RenameModel(
            old_name='Vote',
            new_name='BugVote',
        ),
    ]
